# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#Basically we have two jobs that take the same docker image and run two steps that echo/print words
version: 2.1
#defines the first job
jobs:
  print_hello: #job name
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  #Defines the second job
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
          