#GOod example of how to use attachment of workspace in a prohject
#This one Saves a string of text into a .txt file in some directory through one job and uses another job to
#Access the file in that direcotry and print it.

version: 2.1
#defines the first job
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  #More instructions could come here
  #working_direcotry: ~/project

jobs:
  save_hello_world_output: #job name
    <<: *defaults
    steps:
      - run: echo "Hello World" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  #Defines the second job
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output