#Purposefully creates a failure in a job so that it can be handled by another job
version: 2.1

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: Something Went Wrong
          command: echo "Ops, something failed"
          when: on_fail



workflows:
  my_workflow:
    jobs:
      - my_job